import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Modal from "../components/Modal"
import styled from 'styled-components'

const Home: NextPage = () => {
     const [headerText, setHeaderText] = useState("Heal")
     const [open, setOpen] = useState(false);
     const handleOpen = () => setOpen(true);
     const handleClose = () => setOpen(false);
     const [modalContent, setModalContent] = useState(
     <p>
          Duis mollis, est non commodo luctus, nisi erat porttitor ligula.
     </p>
     )
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <p className={styles.description}>
                    <Buttons  onClick={handleOpen} disabled={false}/>
          </p>

      <Modal 
               modalContent={modalContent} 
               headerText={headerText} 
               open={open}  
               handleOpen={false} 
               setOpen={false} 
               handleClose={handleClose}       
          />
    </div>
  )
}

export default Home

const Buttons = styled.button`
     
`


