import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Modal from "../components/Modal"
import styled from 'styled-components'
import BasicButtons from '../components/Button'

const Home: NextPage = () => {
     const [buttonText, setButtonText] = useState("")
     const [headerText, setHeaderText] = useState("")
     const [open, setOpen] = useState(false);
     const handleOpen = () => setOpen(true);
     const handleClose = () => setOpen(false);
     const [modalContent, setModalContent] = useState(<></>)

     function Check() {
          setHeaderText("Beal")
          setModalContent(
               <>
                    <p>
                         Duis mollis, est non commodo luctus, nisi erat porttitor ligula.
                    </p>
               </>
          )

     }
     function Check1() {
          setHeaderText("heal")
          setModalContent(
               <>
                    <p>
                         Duis mollis, est non commodo luctus, nisi erat porttitor ligula.
                    </p>
               </>
          )

     }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <p className={styles.description}>
                    <BasicButtons ButtonText={'Check'}    onClick={()=> {handleOpen(); Check();}} disabled={false}/>
                    <h1>nill</h1>
                    <BasicButtons ButtonText={'Check1'}   onClick={()=> {handleOpen(); Check1();}} disabled={false}/>
          </p>

      <Modal 
               modalContent={modalContent} 
               headerText={headerText} 
               open={open}  
               handleOpen={false} 
               setOpen={false} 
               handleClose={handleClose}       
          />
    </div>
  )
}

export default Home



